sudo: false

addons:
  apt:
    packages:
    - libav-tools
    - libsndfile1

cache:
  directories:
  - $HOME/env

language: python

notifications:
  email: false

python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"

before_install:
    - bash .travis_dependencies.sh
    - export PATH="$HOME/env/miniconda$TRAVIS_PYTHON_VERSION/bin:$PATH";
    - hash -r
    - source activate test-environment

install:
    # install your own package into the environment
    # pip install -e rather than setup.py, so that coverage can find the source
    - pip install -e ./
    - pip install flake8
    - pip install pytest-cov
    # We can get rid of these once we get rid of 2.7 and 3.5
    - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install black; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then pip install black; fi

script:
    - python --version
    # We can get rid of these once we get rid of 2.7 and 3.5
    - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then black -S --check --verbose .; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then black -S --check --verbose .; fi
    - flake8 --ignore E501,E203 --exclude=tests,docs,build
    - pytest --cov=amen tests/

after_success:
    - coveralls
    - pip uninstall -y amen

after_failure:
    - pip uninstall -y amen
